# Generated by Django 5.1.4 on 2025-01-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist_item_count',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.listings'),
        ),
    ]
